name: Gatsby Publish Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: enriikke/gatsby-gh-pages-action@v2
        env:
          DEPLOY_TYPE: 'staging'
          DEPLOY_PREFIX: techfar-hub-website-v3/
          SITE_URL: https://usds.github.io/techfar-hub-website-v3/
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          working-dir: tech-far-hub
          gatsby-args: --prefix-paths
