name: Gatsby Publish Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: enriikke/gatsby-gh-pages-action@v2
        env:
          SITE_URL: https://techfarhub.usds.gov
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          working-dir: tech-far-hub
